version: '3'

services:
  app:
    build: ./
    image: mean
    expose:
      - 4040
    environment:
      NODE_ENV: production
      SERVER_PORT: 4060
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongo/review-sharing
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:4.9
